import { fetchPullRequest, parsePullRequestUrl } from "./github";
import { createGithubClient } from "./github-auth";
import type { Analysis } from "./types";
import { shouldPublishFinding } from "./profile";
import { verifyAnalysisAttestation } from "./attestation";

export const MERGEPROOF_SUMMARY_START = "<!-- mergeproof-summary:start -->";
export const MERGEPROOF_SUMMARY_END = "<!-- mergeproof-summary:end -->";
export type ReviewPublicationOptions = { requestChangesWorkflow?: boolean; highLevelSummary?: boolean };
export type ApprovalGateResult = { eligible: boolean; reasons: string[] };

export function evaluateApprovalGate(analysis: Analysis, currentHeadSha: string): ApprovalGateResult {
  const reasons: string[] = [];
  if (analysis.decision !== "ready") reasons.push(`decision is ${analysis.decision}`);
  if (!analysis.trace.headSha || analysis.trace.headSha !== currentHeadSha) reasons.push("analysis head SHA does not match the current pull request head");
  if (!verifyAnalysisAttestation(analysis).valid) reasons.push("analysis attestation is missing or invalid");
  if (analysis.trace.unsupportedClaims !== 0) reasons.push(`${analysis.trace.unsupportedClaims} unsupported claim(s)`);
  if ((analysis.trace.blockingFailures ?? 0) !== 0) reasons.push(`${analysis.trace.blockingFailures} blocking failure(s)`);
  if ((analysis.trace.customCheckWarnings ?? 0) !== 0) reasons.push(`${analysis.trace.customCheckWarnings} warning-mode pre-merge exception(s)`);
  if (analysis.rows.some((row) => row.state !== "pass" || row.citations.length === 0)) reasons.push("one or more criteria lack passing, cited evidence");
  if ((analysis.securityFindings ?? []).some((finding) => finding.severity === "high" || finding.severity === "medium")) reasons.push("medium/high security findings remain");
  if ((analysis.qualitySignals ?? []).some((finding) => finding.severity === "high" || finding.severity === "medium")) reasons.push("medium/high quality findings remain");
  return { eligible: reasons.length === 0, reasons };
}

function lineFromCitation(url: string): number {
  return Number(url.match(/#L(\d+)/)?.[1] ?? 1);
}

export function formatPullRequestSummary(analysis: Analysis): string {
  const rows = analysis.rows.map((row) => {
    const citations = row.citations.length ? ` ${row.citations.map((citation) => `[evidence](${citation.url})`).join(" ")}` : "";
    return `- **${row.state.toUpperCase()}** ${row.criterion}: ${row.evidence}${citations}`;
  }).join("\n") || "- No criteria were extracted.";
  const findings = [...(analysis.securityFindings ?? []), ...(analysis.qualitySignals ?? [])].map((finding) => `- **${finding.severity.toUpperCase()}** ${finding.path}:${finding.line} ${finding.title}`).join("\n");
  return [
    MERGEPROOF_SUMMARY_START,
    "## MergeProof review",
    `**Decision:** \`${analysis.decision}\`  `,
    `**Model:** \`${analysis.trace.model}\` | **Mode:** \`${analysis.trace.reviewMode ?? "enforce"}\` | **Verified citations:** ${analysis.trace.citedSources}/${analysis.trace.fetchedSources} | **Unsupported claims:** ${analysis.trace.unsupportedClaims}`,
    ...(analysis.trace.attestation ? [`**Attestation:** \`${analysis.trace.attestation.algorithm}:${analysis.trace.attestation.digest}\``] : []),
    "",
    "### Criteria",
    rows,
    ...(findings ? ["", "### Security and quality", findings] : []),
    "",
    "_This block is generated by MergeProof and can be refreshed safely. See the linked evidence before merging._",
    MERGEPROOF_SUMMARY_END,
  ].join("\n");
}

export function mergePullRequestSummary(body: string | null | undefined, summary: string): string {
  const existing = body ?? "";
  const markerPattern = new RegExp(`${escapeRegExp(MERGEPROOF_SUMMARY_START)}[\\s\\S]*?${escapeRegExp(MERGEPROOF_SUMMARY_END)}`, "m");
  if (markerPattern.test(existing)) return existing.replace(markerPattern, summary);
  return existing.trim() ? `${existing.trimEnd()}\n\n${summary}` : summary;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export async function publishPullRequestSummary(prUrl: string, analysis: Analysis): Promise<string | undefined> {
  const ref = parsePullRequestUrl(prUrl);
  const octokit = await createGithubClient(true);
  const current = await octokit.rest.pulls.get({ owner: ref.owner, repo: ref.repo, pull_number: ref.number });
  const body = mergePullRequestSummary(current.data.body, formatPullRequestSummary(analysis));
  const response = await octokit.rest.pulls.update({ owner: ref.owner, repo: ref.repo, pull_number: ref.number, body });
  return response.data.html_url ?? ref.url;
}

export function reviewEventForDecision(decision: Analysis["decision"], requestChangesWorkflow = true): "APPROVE" | "REQUEST_CHANGES" | "COMMENT" {
  if (decision === "ready") return "APPROVE";
  if (decision === "needs-evidence" && requestChangesWorkflow) return "REQUEST_CHANGES";
  return "COMMENT";
}

export function reviewEventForAnalysis(analysis: Analysis, requestChangesWorkflow = true): "APPROVE" | "REQUEST_CHANGES" | "COMMENT" {
  if (analysis.trace.blockingFailures === 0 && (analysis.trace.customCheckWarnings ?? 0) > 0) return "COMMENT";
  return reviewEventForDecision(analysis.decision, requestChangesWorkflow);
}

export async function publishPullRequestReview(prUrl: string, analysis: Analysis, options: ReviewPublicationOptions = {}): Promise<string | undefined> {
  const ref = parsePullRequestUrl(prUrl);
  const context = await fetchPullRequest(ref);
  const changedPaths = new Set(context.files.map((file) => file.path));
  const profile = analysis.trace.reviewProfile ?? "chill";
  const rows = profile === "quiet" ? analysis.rows.filter((row) => row.state !== "pass") : analysis.rows;
  const comments = rows.flatMap((row) => row.citations.slice(0, 1).filter((citation) => changedPaths.has(citation.path)).map((citation) => ({ path: citation.path, line: lineFromCitation(citation.url), side: "RIGHT" as const, body: `**${row.state.toUpperCase()}**: ${row.evidence}\n\nEvidence: ${citation.url}` })));
  comments.push(...(analysis.securityFindings ?? []).filter((finding) => changedPaths.has(finding.path) && shouldPublishFinding(profile, finding.severity, finding.category)).map((finding) => ({ path: finding.path, line: finding.line, side: "RIGHT" as const, body: `**${(finding.category === "privacy" ? "PRIVACY" : "SECURITY")} ${finding.severity.toUpperCase()}**: ${finding.title}\n\n${finding.detail}\n\nEvidence: ${finding.citation.url}` })));
  comments.push(...(analysis.qualitySignals ?? []).filter((finding) => changedPaths.has(finding.path) && shouldPublishFinding(profile, finding.severity, finding.category)).map((finding) => ({ path: finding.path, line: finding.line, side: "RIGHT" as const, body: `**QUALITY ${finding.severity.toUpperCase()}**: ${finding.title}\n\n${finding.detail}\n\nEvidence: ${finding.citation.url}` })));
  const approvalGate = evaluateApprovalGate(analysis, context.headSha);
  const requestedEvent = reviewEventForAnalysis(analysis, options.requestChangesWorkflow !== false);
  const event = requestedEvent === "APPROVE" && !approvalGate.eligible ? "COMMENT" : requestedEvent;
  const security = (analysis.securityFindings ?? []).map((finding) => `- **${finding.severity.toUpperCase()}** ${finding.path}:${finding.line} ${finding.title}`).join("\n");
  const quality = (analysis.qualitySignals ?? []).map((finding) => `- **${finding.severity.toUpperCase()}** ${finding.path}:${finding.line} ${finding.title}`).join("\n");
  const walkthrough = analysis.walkthrough ? `\n\n### Walkthrough\n${analysis.walkthrough.summary}\n\nChange stack: ${analysis.walkthrough.changeStack.map((layer) => `${layer.title} (${layer.files.length})`).join(" -> ")}\nReview effort: ${analysis.walkthrough.effortScore}/5${analysis.walkthrough.suggestedLabels.length ? `\nSuggested labels: ${analysis.walkthrough.suggestedLabels.join(", ")}` : ""}` : "";
  const gateText = approvalGate.eligible ? "Evidence-gated approval: eligible" : `Evidence-gated approval: withheld (${approvalGate.reasons.join("; ")})`;
  const attestationText = analysis.trace.attestation ? `\nAttestation: ${analysis.trace.attestation.algorithm}:${analysis.trace.attestation.digest}` : "\nAttestation: unavailable";
  const body = `MergeProof decision: **${analysis.decision}**\n\n${options.highLevelSummary === false ? "High-level summary disabled by repository policy.\n\n" : ""}${options.highLevelSummary === false ? "" : security ? `Security/privacy findings:\n${security}\n\n` : ""}${options.highLevelSummary === false ? "" : quality ? `Quality signals:\n${quality}\n\n` : ""}${rows.map((row) => `- **${row.state.toUpperCase()}** ${row.criterion}`).join("\n")}\n\nProfile: ${profile} | Verified citations: ${analysis.trace.citedSources}\nHead SHA: \`${context.headSha}\`\n${gateText}${attestationText}${options.highLevelSummary === false ? "" : walkthrough}`;
  const octokit = await createGithubClient(true);
  try {
    const response = await octokit.rest.pulls.createReview({ owner: ref.owner, repo: ref.repo, pull_number: ref.number, commit_id: context.headSha, body, event, comments: comments.slice(0, 50) });
    return response.data.html_url ?? undefined;
  } catch (error) {
    if (!(error instanceof Error) || !/422|line|diff/i.test(error.message)) throw error;
    const response = await octokit.rest.issues.createComment({ owner: ref.owner, repo: ref.repo, issue_number: ref.number, body });
    return response.data.html_url ?? undefined;
  }
}

export async function publishPullRequestComment(prUrl: string, body: string): Promise<string | undefined> {
  const ref = parsePullRequestUrl(prUrl);
  const octokit = await createGithubClient(true);
  const response = await octokit.rest.issues.createComment({ owner: ref.owner, repo: ref.repo, issue_number: ref.number, body });
  return response.data.html_url ?? undefined;
}

export async function requestPullRequestReviewers(prUrl: string, reviewers: string[]): Promise<string> {
  const ref = parsePullRequestUrl(prUrl);
  const normalized = reviewers.map((reviewer) => reviewer.replace(/^@/, "").trim()).filter(Boolean);
  const users = normalized.filter((reviewer) => !reviewer.startsWith("team:"));
  const teams = normalized.filter((reviewer) => reviewer.startsWith("team:")).map((reviewer) => reviewer.slice("team:".length)).filter(Boolean);
  if (!users.length && !teams.length) throw new Error("At least one GitHub username or team:<slug> reviewer is required.");
  const octokit = await createGithubClient(true);
  await octokit.rest.pulls.requestReviewers({ owner: ref.owner, repo: ref.repo, pull_number: ref.number, ...(users.length ? { reviewers: users } : {}), ...(teams.length ? { team_reviewers: teams } : {}) });
  return ref.url;
}

export async function applyPullRequestLabels(prUrl: string, labels: string[]): Promise<string> {
  const ref = parsePullRequestUrl(prUrl);
  const normalized = [...new Set(labels.map((label) => label.trim()).filter((label) => /^[A-Za-z0-9][A-Za-z0-9:_ -]{0,49}$/.test(label)))].slice(0, 20);
  if (!normalized.length) throw new Error("At least one safe GitHub label is required.");
  const octokit = await createGithubClient(true);
  await octokit.rest.issues.addLabels({ owner: ref.owner, repo: ref.repo, issue_number: ref.number, labels: normalized });
  return ref.url;
}
